# Generated by Django 4.2.1 on 2023-05-04 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
