# Generated by Django 4.2 on 2023-05-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_blog_publish_alter_blog_date_alter_blog_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=255, verbose_name='URL'),
        ),
    ]
