# Generated by Django 4.2.1 on 2025-02-19 06:36

import courses.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order'], 'verbose_name': 'Контент', 'verbose_name_plural': 'Контенты'},
        ),
        migrations.AddField(
            model_name='course',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='module',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='module',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='courses/images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=courses.fields.OrderField(blank=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='module',
            name='url',
            field=models.URLField(default='https://example.com', verbose_name='Ссылка'),
        ),
    ]
