# Generated by Django 4.2.1 on 2025-02-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_content_options_course_updated_module_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
