# Generated by Django 5.0.3 on 2024-04-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_product_structure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-publish'], 'verbose_name': 'Блог', 'verbose_name_plural': 'Блог'},
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2),
        ),
    ]
