# Generated by Django 4.2.1 on 2025-02-18 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Основной текст статьи')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('discountPrice', models.IntegerField(verbose_name='Стоимость со скидкой')),
                ('url', models.URLField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Основной текст')),
            ],
            options={
                'verbose_name': 'Структура',
                'verbose_name_plural': 'Структура',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Название статьи')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL')),
                ('image', models.ImageField(upload_to='media/blog', verbose_name='Изображение')),
                ('text', models.TextField(verbose_name='Основной текст статьи')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('status', models.CharField(choices=[('DF', 'Черновик'), ('PB', 'Опубликовать')], default='DF', max_length=2, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блог',
                'ordering': ['-publish'],
                'indexes': [models.Index(fields=['-publish'], name='main_blog_publish_52a62a_idx')],
            },
        ),
    ]
