# Generated by Django 5.0.3 on 2024-03-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_module_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Основной текст')),
            ],
            options={
                'verbose_name': 'Структура',
                'verbose_name_plural': 'Структура',
            },
        ),
    ]
