# Generated by Django 5.0.3 on 2024-03-12 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_structure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Structure',
        ),
    ]
