# Generated by Django 4.2.2 on 2023-06-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blog_youtube_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='blog',
            name='url',
            field=models.URLField(blank=True, verbose_name='Ссылка'),
        ),
    ]
