# Generated by Django 4.2.2 on 2024-06-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_remove_blog_youtube_url_blog_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[("DF", "Черновик"), ("PB", "Опубликовать")],
                default="DF",
                max_length=2,
                verbose_name="Статус",
            ),
        ),
    ]
