# Generated by Django 4.2 on 2023-05-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_created_alter_course_overview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='image',
            field=models.ImageField(default='image', upload_to='media/courses', verbose_name='Изображение'),
        ),
    ]
