# Generated by Django 4.2.2 on 2023-06-20 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_module_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discountPrice',
        ),
    ]
