# Generated by Django 4.2.2 on 2023-06-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_module_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='image',
            field=models.ImageField(blank=True, default='image', upload_to='media/courses', verbose_name='Изображение'),
        ),
    ]
