# Generated by Django 5.0.3 on 2024-03-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_blog_options_rename_date_blog_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Основной текст статьи')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('discountPrice', models.IntegerField(verbose_name='Стоимость со скидкой')),
                ('url', models.URLField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Основной текст')),
            ],
            options={
                'verbose_name': 'Структура',
                'verbose_name_plural': 'Структура',
            },
        ),
    ]
