# Generated by Django 4.2.1 on 2024-05-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_alter_blog_options_blog_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[("DF", "Черновик"), ("PB", "Опубликовать")],
                default="DF",
                max_length=2,
                verbose_name="Статус",
            ),
        ),
    ]
